default_platform(:mac)

platform :mac do
  desc "Build macOS App"
  lane :app_build do
  ime_path = "/Library/Input Methods"

    build_mac_app(
    configuration: "Debug",
    export_method: "development",
    scheme: "Raelize",
    output_directory: "#{ENV["HOME"]}#{ime_path}",
    clean: true
    )

    sh("pkill", "Raelize")
  end
end
